"use strict";
(function (Gender) {
    Gender[Gender["Male"] = 0] = "Male";
    Gender[Gender["Fifth Plea"] = 1] = "Fifth Plea";
    Gender[Gender["Female"] = 2] = "Female";
})(exports.Gender || (exports.Gender = {}));
var Gender = exports.Gender;
exports.YearsExperience = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "Since it was invented... Yo!"];
(function (JobType) {
    JobType[JobType["Analyst"] = 0] = "Analyst";
    JobType[JobType["Business User"] = 1] = "Business User";
    JobType[JobType["Manager"] = 2] = "Manager";
    JobType[JobType["Coordinator/Specialist"] = 3] = "Coordinator/Specialist";
    JobType[JobType["C-Level"] = 4] = "C-Level";
    JobType[JobType["Developer"] = 5] = "Developer";
    JobType[JobType["VP"] = 6] = "VP";
    JobType[JobType["Other"] = 7] = "Other";
})(exports.JobType || (exports.JobType = {}));
var JobType = exports.JobType;
(function (Country) {
    Country[Country["Afghanistan"] = 0] = "Afghanistan";
    Country[Country["Åland Islands"] = 1] = "Åland Islands";
    Country[Country["Albania"] = 2] = "Albania";
    Country[Country["Algeria"] = 3] = "Algeria";
    Country[Country["American Samoa"] = 4] = "American Samoa";
    Country[Country["Andorra"] = 5] = "Andorra";
    Country[Country["Angola"] = 6] = "Angola";
    Country[Country["Anguilla"] = 7] = "Anguilla";
    Country[Country["Antarctica"] = 8] = "Antarctica";
    Country[Country["Antigua and Barbuda"] = 9] = "Antigua and Barbuda";
    Country[Country["Argentina"] = 10] = "Argentina";
    Country[Country["Armenia"] = 11] = "Armenia";
    Country[Country["Aruba"] = 12] = "Aruba";
    Country[Country["Australia"] = 13] = "Australia";
    Country[Country["Austria"] = 14] = "Austria";
    Country[Country["Azerbaijan"] = 15] = "Azerbaijan";
    Country[Country["Bahamas"] = 16] = "Bahamas";
    Country[Country["Bahrain"] = 17] = "Bahrain";
    Country[Country["Bangladesh"] = 18] = "Bangladesh";
    Country[Country["Barbados"] = 19] = "Barbados";
    Country[Country["Belarus"] = 20] = "Belarus";
    Country[Country["Belgium"] = 21] = "Belgium";
    Country[Country["Belize"] = 22] = "Belize";
    Country[Country["Benin"] = 23] = "Benin";
    Country[Country["Bermuda"] = 24] = "Bermuda";
    Country[Country["Bhutan"] = 25] = "Bhutan";
    Country[Country["Bolivia"] = 26] = "Bolivia";
    Country[Country["Bosnia and Herzegovina"] = 27] = "Bosnia and Herzegovina";
    Country[Country["Botswana"] = 28] = "Botswana";
    Country[Country["Bouvet Island"] = 29] = "Bouvet Island";
    Country[Country["Brazil"] = 30] = "Brazil";
    Country[Country["British Indian Ocean Territory"] = 31] = "British Indian Ocean Territory";
    Country[Country["Brunei Darussalam"] = 32] = "Brunei Darussalam";
    Country[Country["Bulgaria"] = 33] = "Bulgaria";
    Country[Country["Burkina Faso"] = 34] = "Burkina Faso";
    Country[Country["Burundi"] = 35] = "Burundi";
    Country[Country["Cambodia"] = 36] = "Cambodia";
    Country[Country["Cameroon"] = 37] = "Cameroon";
    Country[Country["Canada"] = 38] = "Canada";
    Country[Country["Cape Verde"] = 39] = "Cape Verde";
    Country[Country["Cayman Islands"] = 40] = "Cayman Islands";
    Country[Country["Central African Republic"] = 41] = "Central African Republic";
    Country[Country["Chad"] = 42] = "Chad";
    Country[Country["Chile"] = 43] = "Chile";
    Country[Country["China"] = 44] = "China";
    Country[Country["Christmas Island"] = 45] = "Christmas Island";
    Country[Country["Cocos (Keeling) Islands"] = 46] = "Cocos (Keeling) Islands";
    Country[Country["Colombia"] = 47] = "Colombia";
    Country[Country["Comoros"] = 48] = "Comoros";
    Country[Country["Congo"] = 49] = "Congo";
    Country[Country["Congo, The Democratic Republic of The"] = 50] = "Congo, The Democratic Republic of The";
    Country[Country["Cook Islands"] = 51] = "Cook Islands";
    Country[Country["Costa Rica"] = 52] = "Costa Rica";
    Country[Country["Cote D'ivoire"] = 53] = "Cote D'ivoire";
    Country[Country["Croatia"] = 54] = "Croatia";
    Country[Country["Cuba"] = 55] = "Cuba";
    Country[Country["Cyprus"] = 56] = "Cyprus";
    Country[Country["Czech Republic"] = 57] = "Czech Republic";
    Country[Country["Denmark"] = 58] = "Denmark";
    Country[Country["Djibouti"] = 59] = "Djibouti";
    Country[Country["Dominica"] = 60] = "Dominica";
    Country[Country["Dominican Republic"] = 61] = "Dominican Republic";
    Country[Country["Ecuador"] = 62] = "Ecuador";
    Country[Country["Egypt"] = 63] = "Egypt";
    Country[Country["El Salvador"] = 64] = "El Salvador";
    Country[Country["Equatorial Guinea"] = 65] = "Equatorial Guinea";
    Country[Country["Eritrea"] = 66] = "Eritrea";
    Country[Country["Estonia"] = 67] = "Estonia";
    Country[Country["Ethiopia"] = 68] = "Ethiopia";
    Country[Country["Falkland Islands (Malvinas)"] = 69] = "Falkland Islands (Malvinas)";
    Country[Country["Faroe Islands"] = 70] = "Faroe Islands";
    Country[Country["Fiji"] = 71] = "Fiji";
    Country[Country["Finland"] = 72] = "Finland";
    Country[Country["France"] = 73] = "France";
    Country[Country["French Guiana"] = 74] = "French Guiana";
    Country[Country["French Polynesia"] = 75] = "French Polynesia";
    Country[Country["French Southern Territories"] = 76] = "French Southern Territories";
    Country[Country["Gabon"] = 77] = "Gabon";
    Country[Country["Gambia"] = 78] = "Gambia";
    Country[Country["Georgia"] = 79] = "Georgia";
    Country[Country["Germany"] = 80] = "Germany";
    Country[Country["Ghana"] = 81] = "Ghana";
    Country[Country["Gibraltar"] = 82] = "Gibraltar";
    Country[Country["Greece"] = 83] = "Greece";
    Country[Country["Greenland"] = 84] = "Greenland";
    Country[Country["Grenada"] = 85] = "Grenada";
    Country[Country["Guadeloupe"] = 86] = "Guadeloupe";
    Country[Country["Guam"] = 87] = "Guam";
    Country[Country["Guatemala"] = 88] = "Guatemala";
    Country[Country["Guernsey"] = 89] = "Guernsey";
    Country[Country["Guinea"] = 90] = "Guinea";
    Country[Country["Guinea-bissau"] = 91] = "Guinea-bissau";
    Country[Country["Guyana"] = 92] = "Guyana";
    Country[Country["Haiti"] = 93] = "Haiti";
    Country[Country["Heard Island and Mcdonald Islands"] = 94] = "Heard Island and Mcdonald Islands";
    Country[Country["Holy See (Vatican City State)"] = 95] = "Holy See (Vatican City State)";
    Country[Country["Honduras"] = 96] = "Honduras";
    Country[Country["Hong Kong"] = 97] = "Hong Kong";
    Country[Country["Hungary"] = 98] = "Hungary";
    Country[Country["Iceland"] = 99] = "Iceland";
    Country[Country["India"] = 100] = "India";
    Country[Country["Indonesia"] = 101] = "Indonesia";
    Country[Country["Iran, Islamic Republic of"] = 102] = "Iran, Islamic Republic of";
    Country[Country["Iraq"] = 103] = "Iraq";
    Country[Country["Ireland"] = 104] = "Ireland";
    Country[Country["Isle of Man"] = 105] = "Isle of Man";
    Country[Country["Israel"] = 106] = "Israel";
    Country[Country["Italy"] = 107] = "Italy";
    Country[Country["Jamaica"] = 108] = "Jamaica";
    Country[Country["Japan"] = 109] = "Japan";
    Country[Country["Jersey"] = 110] = "Jersey";
    Country[Country["Jordan"] = 111] = "Jordan";
    Country[Country["Kazakhstan"] = 112] = "Kazakhstan";
    Country[Country["Kenya"] = 113] = "Kenya";
    Country[Country["Kiribati"] = 114] = "Kiribati";
    Country[Country["Korea, Democratic People's Republic of"] = 115] = "Korea, Democratic People's Republic of";
    Country[Country["Korea, Republic of"] = 116] = "Korea, Republic of";
    Country[Country["Kuwait"] = 117] = "Kuwait";
    Country[Country["Kyrgyzstan"] = 118] = "Kyrgyzstan";
    Country[Country["Lao People's Democratic Republic"] = 119] = "Lao People's Democratic Republic";
    Country[Country["Latvia"] = 120] = "Latvia";
    Country[Country["Lebanon"] = 121] = "Lebanon";
    Country[Country["Lesotho"] = 122] = "Lesotho";
    Country[Country["Liberia"] = 123] = "Liberia";
    Country[Country["Libyan Arab Jamahiriya"] = 124] = "Libyan Arab Jamahiriya";
    Country[Country["Liechtenstein"] = 125] = "Liechtenstein";
    Country[Country["Lithuania"] = 126] = "Lithuania";
    Country[Country["Luxembourg"] = 127] = "Luxembourg";
    Country[Country["Macao"] = 128] = "Macao";
    Country[Country["Macedonia, The Former Yugoslav Republic of"] = 129] = "Macedonia, The Former Yugoslav Republic of";
    Country[Country["Madagascar"] = 130] = "Madagascar";
    Country[Country["Malawi"] = 131] = "Malawi";
    Country[Country["Malaysia"] = 132] = "Malaysia";
    Country[Country["Maldives"] = 133] = "Maldives";
    Country[Country["Mali"] = 134] = "Mali";
    Country[Country["Malta"] = 135] = "Malta";
    Country[Country["Marshall Islands"] = 136] = "Marshall Islands";
    Country[Country["Martinique"] = 137] = "Martinique";
    Country[Country["Mauritania"] = 138] = "Mauritania";
    Country[Country["Mauritius"] = 139] = "Mauritius";
    Country[Country["Mayotte"] = 140] = "Mayotte";
    Country[Country["Mexico"] = 141] = "Mexico";
    Country[Country["Micronesia, Federated States of"] = 142] = "Micronesia, Federated States of";
    Country[Country["Moldova, Republic of"] = 143] = "Moldova, Republic of";
    Country[Country["Monaco"] = 144] = "Monaco";
    Country[Country["Mongolia"] = 145] = "Mongolia";
    Country[Country["Montenegro"] = 146] = "Montenegro";
    Country[Country["Montserrat"] = 147] = "Montserrat";
    Country[Country["Morocco"] = 148] = "Morocco";
    Country[Country["Mozambique"] = 149] = "Mozambique";
    Country[Country["Myanmar"] = 150] = "Myanmar";
    Country[Country["Namibia"] = 151] = "Namibia";
    Country[Country["Nauru"] = 152] = "Nauru";
    Country[Country["Nepal"] = 153] = "Nepal";
    Country[Country["Netherlands"] = 154] = "Netherlands";
    Country[Country["Netherlands Antilles"] = 155] = "Netherlands Antilles";
    Country[Country["New Caledonia"] = 156] = "New Caledonia";
    Country[Country["New Zealand"] = 157] = "New Zealand";
    Country[Country["Nicaragua"] = 158] = "Nicaragua";
    Country[Country["Niger"] = 159] = "Niger";
    Country[Country["Nigeria"] = 160] = "Nigeria";
    Country[Country["Niue"] = 161] = "Niue";
    Country[Country["Norfolk Island"] = 162] = "Norfolk Island";
    Country[Country["Northern Mariana Islands"] = 163] = "Northern Mariana Islands";
    Country[Country["Norway"] = 164] = "Norway";
    Country[Country["Oman"] = 165] = "Oman";
    Country[Country["Pakistan"] = 166] = "Pakistan";
    Country[Country["Palau"] = 167] = "Palau";
    Country[Country["Palestinian Territory, Occupied"] = 168] = "Palestinian Territory, Occupied";
    Country[Country["Panama"] = 169] = "Panama";
    Country[Country["Papua New Guinea"] = 170] = "Papua New Guinea";
    Country[Country["Paraguay"] = 171] = "Paraguay";
    Country[Country["Peru"] = 172] = "Peru";
    Country[Country["Philippines"] = 173] = "Philippines";
    Country[Country["Pitcairn"] = 174] = "Pitcairn";
    Country[Country["Poland"] = 175] = "Poland";
    Country[Country["Portugal"] = 176] = "Portugal";
    Country[Country["Puerto Rico"] = 177] = "Puerto Rico";
    Country[Country["Qatar"] = 178] = "Qatar";
    Country[Country["Reunion"] = 179] = "Reunion";
    Country[Country["Romania"] = 180] = "Romania";
    Country[Country["Russian Federation"] = 181] = "Russian Federation";
    Country[Country["Rwanda"] = 182] = "Rwanda";
    Country[Country["Saint Helena"] = 183] = "Saint Helena";
    Country[Country["Saint Kitts and Nevis"] = 184] = "Saint Kitts and Nevis";
    Country[Country["Saint Lucia"] = 185] = "Saint Lucia";
    Country[Country["Saint Pierre and Miquelon"] = 186] = "Saint Pierre and Miquelon";
    Country[Country["Saint Vincent and The Grenadines"] = 187] = "Saint Vincent and The Grenadines";
    Country[Country["Samoa"] = 188] = "Samoa";
    Country[Country["San Marino"] = 189] = "San Marino";
    Country[Country["Sao Tome and Principe"] = 190] = "Sao Tome and Principe";
    Country[Country["Saudi Arabia"] = 191] = "Saudi Arabia";
    Country[Country["Senegal"] = 192] = "Senegal";
    Country[Country["Serbia"] = 193] = "Serbia";
    Country[Country["Seychelles"] = 194] = "Seychelles";
    Country[Country["Sierra Leone"] = 195] = "Sierra Leone";
    Country[Country["Singapore"] = 196] = "Singapore";
    Country[Country["Slovakia"] = 197] = "Slovakia";
    Country[Country["Slovenia"] = 198] = "Slovenia";
    Country[Country["Solomon Islands"] = 199] = "Solomon Islands";
    Country[Country["Somalia"] = 200] = "Somalia";
    Country[Country["South Africa"] = 201] = "South Africa";
    Country[Country["South Georgia and The South Sandwich Islands"] = 202] = "South Georgia and The South Sandwich Islands";
    Country[Country["Spain"] = 203] = "Spain";
    Country[Country["Sri Lanka"] = 204] = "Sri Lanka";
    Country[Country["Sudan"] = 205] = "Sudan";
    Country[Country["Suriname"] = 206] = "Suriname";
    Country[Country["Svalbard and Jan Mayen"] = 207] = "Svalbard and Jan Mayen";
    Country[Country["Swaziland"] = 208] = "Swaziland";
    Country[Country["Sweden"] = 209] = "Sweden";
    Country[Country["Switzerland"] = 210] = "Switzerland";
    Country[Country["Syrian Arab Republic"] = 211] = "Syrian Arab Republic";
    Country[Country["Taiwan, Province of China"] = 212] = "Taiwan, Province of China";
    Country[Country["Tajikistan"] = 213] = "Tajikistan";
    Country[Country["Tanzania, United Republic of"] = 214] = "Tanzania, United Republic of";
    Country[Country["Thailand"] = 215] = "Thailand";
    Country[Country["Timor-leste"] = 216] = "Timor-leste";
    Country[Country["Togo"] = 217] = "Togo";
    Country[Country["Tokelau"] = 218] = "Tokelau";
    Country[Country["Tonga"] = 219] = "Tonga";
    Country[Country["Trinidad and Tobago"] = 220] = "Trinidad and Tobago";
    Country[Country["Tunisia"] = 221] = "Tunisia";
    Country[Country["Turkey"] = 222] = "Turkey";
    Country[Country["Turkmenistan"] = 223] = "Turkmenistan";
    Country[Country["Turks and Caicos Islands"] = 224] = "Turks and Caicos Islands";
    Country[Country["Tuvalu"] = 225] = "Tuvalu";
    Country[Country["Uganda"] = 226] = "Uganda";
    Country[Country["Ukraine"] = 227] = "Ukraine";
    Country[Country["United Arab Emirates"] = 228] = "United Arab Emirates";
    Country[Country["United Kingdom"] = 229] = "United Kingdom";
    Country[Country["United States"] = 230] = "United States";
    Country[Country["United States Minor Outlying Islands"] = 231] = "United States Minor Outlying Islands";
    Country[Country["Uruguay"] = 232] = "Uruguay";
    Country[Country["Uzbekistan"] = 233] = "Uzbekistan";
    Country[Country["Vanuatu"] = 234] = "Vanuatu";
    Country[Country["Venezuela"] = 235] = "Venezuela";
    Country[Country["Viet Nam"] = 236] = "Viet Nam";
    Country[Country["Virgin Islands, British"] = 237] = "Virgin Islands, British";
    Country[Country["Virgin Islands, U.S."] = 238] = "Virgin Islands, U.S.";
    Country[Country["Wallis and Futuna"] = 239] = "Wallis and Futuna";
    Country[Country["Western Sahara"] = 240] = "Western Sahara";
    Country[Country["Yemen"] = 241] = "Yemen";
    Country[Country["Zambia"] = 242] = "Zambia";
    Country[Country["Zimbabwe"] = 243] = "Zimbabwe";
})(exports.Country || (exports.Country = {}));
var Country = exports.Country;
//# sourceMappingURL=Player.js.map